'use strict';
/*!
 *
 * @module config
 * @author jg
 * @date 
 * @version V1.0.0
 * @require
 */

 define([
   'layerManage'
 ], function(layerManage) {
  var cmsLayer = {
    'layers': [],
    'nodes': [
      {
        "name": "无锡市人民医院",
        "checked": false,
        "nocheck": false,
        "halfCheck": false,
        "open": true,
        "sid": 1015,
        "controlUnitId": 91,
        "parentId": 52,
        "indexCode": "320201",
        "sequenceIdx": 2,
        "children": [
          {
            "name": "E区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1650,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "E区01楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/E区/E区01楼/0.c3s.zip",
                "cameraUrl": "camera/E区1F监控/model/0.c3s.zip"
              },
              {
                "name": "E区02楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/E区/E区02楼/0.c3s.zip",
                "cameraUrl": "camera/E区2F监控/model/0.c3s.zip"
              },
              {
                "name": "BC区03层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1251,
                "indexCode": "32020100002160208377",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 396,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "bim_server/320200/E区/E区03楼/0.c3s.zip",
                "cameraUrl": "camera/E区3F监控/model/0.c3s.zip"
              },
              {
                "name": "E区设备层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1316,
                "indexCode": "32020100002160132253",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 397,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "bim_server/320200/E区/E区设备层/0.c3s.zip",
                "cameraUrl": "camera/E区设备层监控/model/0.c3s.zip"
              }
            ]
          },
          {
            "name": "G区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1665,
            "indexCode": "32020100002160687166",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 287,
            "regionLevel": 0,
            "sequenceIdx": 21,
            "children": [
              {
                "name": "G区01楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1042,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/G区/G区01楼/0.c3s.zip",
                "cameraUrl": "camera/G区1F监控/0.c3s.zip"
              },
              {
                "name": "G区02楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1043,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/G区/G区02楼/0.c3s.zip",
                "cameraUrl": "camera/G区2F监控/0.c3s.zip"
              },
              {
                "name": "G区03楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1044,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/G区/G区03楼/0.c3s.zip",
                "cameraUrl": "camera/G区3F监控/0.c3s.zip"
              },
              {
                "name": "G区设备层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1045,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/G区/G区设备层/0.c3s.zip",
                "cameraUrl": "camera/G区设备层监控/0.c3s.zip"
              },
              {
                "name": "G区04楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1041,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/G区/G区04楼/0.c3s.zip",
                "cameraUrl": "camera/G区4F监控/model/0.c3s.zip"
              },
              {
                "name": "G区05楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1156,
                "indexCode": "32020100002160009837",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 300,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/G区/G区05楼/0.c3s.zip",
                "cameraUrl": "camera/G区5F监控/model/0.c3s.zip"
              },
              {
                "name": "G区06楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1238,
                "indexCode": "32020100002160552485",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 302,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "bim_server/320200/G区/G区06楼/0.c3s.zip",
                "cameraUrl": "camera/G区6F监控/model/0.c3s.zip"
              },
              {
                "name": "G区07楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1311,
                "indexCode": "32020100002160343416",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 355,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "bim_server/320200/G区/G区07楼/0.c3s.zip",
                "cameraUrl": "camera/G区7F监控/model/0.c3s.zip"
              },
              {
                "name": "G区08楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1366,
                "indexCode": "32020100002160657540",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 353,
                "regionLevel": 1,
                "sequenceIdx": 4,
                "modelUrl": "bim_server/320200/G区/G区08楼/0.c3s.zip",
                "cameraUrl": "camera/G区8F监控/model/0.c3s.zip"
              },
              {
                "name": "G区09楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1427,
                "indexCode": "32020100002160951872",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 641,
                "regionLevel": 1,
                "sequenceIdx": 5,
                "modelUrl": "bim_server/320200/G区/G区09楼/0.c3s.zip",
                "cameraUrl": "camera/G区9F监控/model/0.c3s.zip"
              },
              {
                "name": "G区10楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1456,
                "indexCode": "32020100002160178366",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 364,
                "regionLevel": 1,
                "sequenceIdx": 6,
                "modelUrl": "bim_server/320200/G区/G区10楼/0.c3s.zip",
                "cameraUrl": "camera/G区10F监控/model/0.c3s.zip"
              },
              {
                "name": "G区11楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1487,
                "indexCode": "32020100002160046699",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 362,
                "regionLevel": 1,
                "sequenceIdx": 7,
                "modelUrl": "bim_server/320200/G区/G区11楼/0.c3s.zip",
                "cameraUrl": "camera/G区11F监控/model/0.c3s.zip"
              }
              // {
              //   "name": "09层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1510,
              //   "indexCode": "32020100002160498570",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 301,
              //   "regionLevel": 1,
              //   "sequenceIdx": 8,
              //   "modelUrl": "bim_server/320200/D栋/09层/0.c3s.zip",
              //   "cameraUrl": "camera/D区9F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "10层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1533,
              //   "indexCode": "32020100002160561555",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 295,
              //   "regionLevel": 1,
              //   "sequenceIdx": 9,
              //   "modelUrl": "bim_server/320200/D栋/10层/0.c3s.zip",
              //   "cameraUrl": "camera/D区10F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "11层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1554,
              //   "indexCode": "32020100002160111093",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 292,
              //   "regionLevel": 1,
              //   "sequenceIdx": 10,
              //   "modelUrl": "bim_server/320200/D栋/11层/0.c3s.zip",
              //   "cameraUrl": "camera/D区11F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "12层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1570,
              //   "indexCode": "32020100002160623230",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 294,
              //   "regionLevel": 1,
              //   "sequenceIdx": 11,
              //   "modelUrl": "bim_server/320200/D栋/12层/0.c3s.zip",
              //   "cameraUrl": "camera/D区12F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "13层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1584,
              //   "indexCode": "32020100002160349620",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 299,
              //   "regionLevel": 1,
              //   "sequenceIdx": 12,
              //   "modelUrl": "bim_server/320200/D栋/13层/0.c3s.zip",
              //   "cameraUrl": "camera/D区13F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "14层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1598,
              //   "indexCode": "32020100002160958948",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 281,
              //   "regionLevel": 1,
              //   "sequenceIdx": 13,
              //   "modelUrl": "bim_server/320200/D栋/14层/0.c3s.zip",
              //   "cameraUrl": "camera/D区14F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "15层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1608,
              //   "indexCode": "32020100002160997784",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 280,
              //   "regionLevel": 1,
              //   "sequenceIdx": 14,
              //   "modelUrl": "bim_server/320200/D栋/15层/0.c3s.zip",
              //   "cameraUrl": "camera/D区15F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "16层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1618,
              //   "indexCode": "32020100002160684696",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 288,
              //   "regionLevel": 1,
              //   "sequenceIdx": 15,
              //   "modelUrl": "bim_server/320200/D栋/16层/0.c3s.zip",
              //   "cameraUrl": "camera/D区16F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "17层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1633,
              //   "indexCode": "32020100002160349076",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 743,
              //   "regionLevel": 1,
              //   "sequenceIdx": 16,
              //   "modelUrl": "bim_server/320200/D栋/17层/0.c3s.zip",
              //   "cameraUrl": "camera/D区17F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "18层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1636,
              //   "indexCode": "32020100002160402001",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 304,
              //   "regionLevel": 1,
              //   "sequenceIdx": 17,
              //   "modelUrl": "bim_server/320200/D栋/18层/0.c3s.zip",
              //   "cameraUrl": "camera/D区18F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "19层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1642,
              //   "indexCode": "32020100002160607761",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 365,
              //   "regionLevel": 1,
              //   "sequenceIdx": 18,
              //   "modelUrl": "bim_server/320200/D栋/19层/0.c3s.zip",
              //   "cameraUrl": "camera/D区19F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "20层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1649,
              //   "indexCode": "32020100002160927342",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 363,
              //   "regionLevel": 1,
              //   "sequenceIdx": 19,
              //   "modelUrl": "bim_server/320200/D栋/20层/0.c3s.zip",
              //   "cameraUrl": "camera/D区20F监控/model/0.c3s.zip"
              // },
              // {
              //   "name": "20顶层",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1659,
              //   "indexCode": "32020100002160635559",
              //   "controlUnitId": 91,
              //   "parentRegionId": 287,
              //   "regionId": 500,
              //   "regionLevel": 1,
              //   "sequenceIdx": 20,
              //   "modelUrl": "bim_server/320200/D栋/20层顶/0.c3s.zip",
              //   "cameraUrl": "camera/D区地下室监控/model/0.c3s.zip"
              // }
            ]
          },
          {
            "name": "J区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1705,
            "indexCode": "32020100002160372936",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 661,
            "regionLevel": 0,
            "sequenceIdx": 30,
            "children": [
              {
                "name": "J区01楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/J区/J区01楼/0.c3s.zip",
                "cameraUrl": "camera/J区1层监控/model/0.c3s.zip"
              },
              {
                "name": "J区02楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1273,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/J区/J区02楼/0.c3s.zip",
                "cameraUrl": "camera/J区2层监控/model/0.c3s.zip"
              },
              {
                "name": "J区03楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1274,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "bim_server/320200/J区/J区03楼/0.c3s.zip",
                "cameraUrl": "camera/J区3层监控/model/0.c3s.zip"
              },
              {
                "name": "J区04楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1275,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "bim_server/320200/J区/J区04楼/0.c3s.zip",
                "cameraUrl": "camera/J区4层监控/model/0.c3s.zip"
              }
            ]
          },
          {
            "name": "T区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1856,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "T区04楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1857,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区04楼/0.c3s.zip",
                "cameraUrl": "camera/T区4层监控/model/0.c3s.zip"
              },
              {
                "name": "T区05楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1858,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区05楼/0.c3s.zip",
                "cameraUrl": "camera/T区5层监控/model/0.c3s.zip"
              },
              {
                "name": "T区06楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1859,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区06楼/0.c3s.zip",
                "cameraUrl": "camera/T区6层监控/model/0.c3s.zip"
              },
              {
                "name": "T区07楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1900,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区07楼/0.c3s.zip",
                "cameraUrl": "camera/T区7层监控/model/0.c3s.zip"
              },
              {
                "name": "T区08楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1901,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区08楼/0.c3s.zip",
                "cameraUrl": "camera/T区8层监控/model/0.c3s.zip"
              },
              {
                "name": "T区09楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1902,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区09楼/0.c3s.zip",
                "cameraUrl": "camera/T区9层监控/model/0.c3s.zip"
              },
              {
                "name": "T区10楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1903,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/T区/T区10楼/0.c3s.zip",
                "cameraUrl": "camera/T区10层监控/model/0.c3s.zip"
              }
            ]
          },
          {
            "name": "A区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 2156,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "A区01楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2157,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/A区/A区01楼/0.c3s.zip",
                "cameraUrl": "camera/A区1F监控/model/0.c3s.zip"
              },
              {
                "name": "A区02楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2158,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/A区/A区02楼/0.c3s.zip",
                "cameraUrl": "camera/A区2F监控/model/0.c3s.zip"
              },
              {
                "name": "A区03楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2159,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/A区/A区03楼/0.c3s.zip",
                "cameraUrl": "camera/A区3F监控/model/0.c3s.zip"
              },
              {
                "name": "A区04楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2160,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/A区/A区04楼/0.c3s.zip",
                "cameraUrl": "camera/A区4F监控/model/0.c3s.zip"
              },
              {
                "name": "A区05楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2161,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/A区/A区05楼/0.c3s.zip",
                "cameraUrl": "camera/A区5F监控/model/0.c3s.zip"
              },
            ]
          },
          {
            "name": "地下室",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1655,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "E区地下室",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1159,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/地下室/E区地下室/0.c3s.zip",
                "cameraUrl": "camera/E区地下室监控/model/0.c3s.zip"
              },
              {
                "name": "G区-1楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1160,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/地下室/G区-1楼/0.c3s.zip",
                "cameraUrl": "camera/G区-1F监控/0.c3s.zip"
              },
              {
                "name": "G区-2楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1161,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/地下室/G区-2楼/0.c3s.zip",
                "cameraUrl": "camera/G区-2F监控/0.c3s.zip"
              },
              {
                "name": "F区地下室",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1163,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/地下室/F区地下室/0.c3s.zip",
                "cameraUrl": "camera/F区地下室监控/model/0.c3s.zip"
              },
              // {
              //   "name": "D区地下室",
              //   "checked": false,
              //   "nocheck": false,
              //   "isParent": false,
              //   "sid": 1277,
              //   "indexCode": "32020100002160259060",
              //   "controlUnitId": 91,
              //   "parentRegionId": 370,
              //   "regionId": 395,
              //   "regionLevel": 1,
              //   "sequenceIdx": 1,
              //   "modelUrl": "bim_server/320200/地下室/D区地下室/0.c3s.zip",
              //   "cameraUrl": "camera/D区地下室监控/model/0.c3s.zip"
              // }
            ]
          },
          {
            "name": "X区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 3655,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "X区04楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3656,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区04楼/0.c3s.zip",
                "cameraUrl": "camera/X区4层监控/0.c3s.zip"
              },
              {
                "name": "X区05楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3657,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区05楼/0.c3s.zip",
                "cameraUrl": "camera/X区5层监控/0.c3s.zip"
              },
              {
                "name": "X区06楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3658,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区06楼/0.c3s.zip",
                "cameraUrl": "camera/X区6层监控/0.c3s.zip"
              },
              {
                "name": "X区07楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3659,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区07楼/0.c3s.zip",
                "cameraUrl": "camera/X区7层监控/0.c3s.zip"
              },
              {
                "name": "X区08楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3700,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区08楼/0.c3s.zip",
                "cameraUrl": "camera/X区8层监控/0.c3s.zip"
              },
              {
                "name": "X区09楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3701,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区09楼/0.c3s.zip",
                "cameraUrl": "camera/X区9层监控/0.c3s.zip"
              },
              {
                "name": "X区10楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3702,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区10楼/0.c3s.zip",
                "cameraUrl": "camera/X区10层监控/0.c3s.zip"
              },
              {
                "name": "X区11楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3703,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区11楼/0.c3s.zip",
                "cameraUrl": "camera/X区11层监控/0.c3s.zip"
              },
              {
                "name": "X区12楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 3704,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/X区/X区12楼/0.c3s.zip",
                "cameraUrl": "camera/X区12层监控/0.c3s.zip"
              },
            ]
          },
          {
            "name": "F区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 4655,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "F区01楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 4704,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/F区/F区01楼/0.c3s.zip",
                "cameraUrl": "camera/F区1F监控/0.c3s.zip"
              },
              {
                "name": "F区03楼",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 4706,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/F区/F区03楼/0.c3s.zip",
                "cameraUrl": "camera/F区2F监控/0.c3s.zip"
              },
              {
                "name": "F区04楼临时",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 4705,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/F区/F区04楼临时/0.c3s.zip",
                "cameraUrl": "camera/F区3F监控/0.c3s.zip"
              },
            ]
          }
        ]
      }
    ]
  };
  var util = {
    'licenceIP': '192.168.10.34@9059@',
    'SDKPath': '',
    'cmsUrl': 'http://192.168.10.194:8088/files/wuxi_yiyuan/',
    'zTreeObj': null,
  };
  var dom = {
    'domUrl': '/320200/320200/DOM/2018050700',
    'range': [120.311622619629,31.5372848510742,120.324668884277,31.5486145019531],
    'minLevel': 0,
    'maxLevel': 22
  };
  var fullMap = {
    'lon': 120.3192458,
    'lat': 31.54294968,
    'height': 60,
    'azimuth': 4.351113551310101,
    'pitch': -0.6722756375833641,
    'range': 300.9511815746299,
    'time': 3
  };
  // ztree 配置
  var setting = {
    check : {
      enable : true,
      autoCheckTrigger : true
    },
    view : {
      showLine : false
    },
    callback : {
      onCheck : layerManage.showHide,
      onDblClick : layerManage.flyToLayer
    }
  };
  return {
    cmsLayer: cmsLayer,
    util: util,
    dom: dom,
    fullMap: fullMap,
    setting: setting
  }
 });