'use strict';
/*!
 *
 * @module config
 * @author jg
 * @date 
 * @version V1.0.0
 * @require
 */

 define([
   'jquery',
   'zTree'
 ], function() {
  var cmsLayer = {
    'layers': [],
    'nodes': [
      {
        "name": "无锡市人民医院",
        "checked": false,
        "nocheck": false,
        "halfCheck": false,
        "open": true,
        "sid": 1015,
        "controlUnitId": 91,
        "parentId": 52,
        "indexCode": "320201",
        "sequenceIdx": 2,
        "children": [
          {
            "name": "B区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1650,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "B区01层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "B区02层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "B区03层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1251,
                "indexCode": "32020100002160208377",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 396,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "B区04层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1316,
                "indexCode": "32020100002160132253",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 397,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "",
                "cameraUrl": ""
              }
            ]
          },
          {
            "name": "C区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1657,
            "indexCode": "32020100002160650790",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 391,
            "regionLevel": 0,
            "sequenceIdx": 20,
            "children": [
              {
                "name": "C区01层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1058,
                "indexCode": "32020100002160138934",
                "controlUnitId": 91,
                "parentRegionId": 391,
                "regionId": 393,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "C区02层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1174,
                "indexCode": "32020100002160990392",
                "controlUnitId": 91,
                "parentRegionId": 391,
                "regionId": 399,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "C区03层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1252,
                "indexCode": "32020100002160081584",
                "controlUnitId": 91,
                "parentRegionId": 391,
                "regionId": 398,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "C区04层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1315,
                "indexCode": "32020100002160453674",
                "controlUnitId": 91,
                "parentRegionId": 391,
                "regionId": 392,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "",
                "cameraUrl": ""
              }
            ]
          },
          {
            "name": "D栋",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1665,
            "indexCode": "32020100002160687166",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 287,
            "regionLevel": 0,
            "sequenceIdx": 21,
            "children": [
              {
                "name": "01层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1041,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "02层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1156,
                "indexCode": "32020100002160009837",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 300,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "03层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1238,
                "indexCode": "32020100002160552485",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 302,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "04层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1311,
                "indexCode": "32020100002160343416",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 355,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "05层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1366,
                "indexCode": "32020100002160657540",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 353,
                "regionLevel": 1,
                "sequenceIdx": 4,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "06层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1427,
                "indexCode": "32020100002160951872",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 641,
                "regionLevel": 1,
                "sequenceIdx": 5,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "07层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1456,
                "indexCode": "32020100002160178366",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 364,
                "regionLevel": 1,
                "sequenceIdx": 6,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "08层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1487,
                "indexCode": "32020100002160046699",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 362,
                "regionLevel": 1,
                "sequenceIdx": 7,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "09层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1510,
                "indexCode": "32020100002160498570",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 301,
                "regionLevel": 1,
                "sequenceIdx": 8,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "10层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1533,
                "indexCode": "32020100002160561555",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 295,
                "regionLevel": 1,
                "sequenceIdx": 9,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "11层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1554,
                "indexCode": "32020100002160111093",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 292,
                "regionLevel": 1,
                "sequenceIdx": 10,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "12层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1570,
                "indexCode": "32020100002160623230",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 294,
                "regionLevel": 1,
                "sequenceIdx": 11,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "13层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1584,
                "indexCode": "32020100002160349620",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 299,
                "regionLevel": 1,
                "sequenceIdx": 12,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "14层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1598,
                "indexCode": "32020100002160958948",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 281,
                "regionLevel": 1,
                "sequenceIdx": 13,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "15层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1608,
                "indexCode": "32020100002160997784",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 280,
                "regionLevel": 1,
                "sequenceIdx": 14,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "16层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1618,
                "indexCode": "32020100002160684696",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 288,
                "regionLevel": 1,
                "sequenceIdx": 15,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "17层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1633,
                "indexCode": "32020100002160349076",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 743,
                "regionLevel": 1,
                "sequenceIdx": 16,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "18层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1636,
                "indexCode": "32020100002160402001",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 304,
                "regionLevel": 1,
                "sequenceIdx": 17,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "19层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1642,
                "indexCode": "32020100002160607761",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 365,
                "regionLevel": 1,
                "sequenceIdx": 18,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "20层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1649,
                "indexCode": "32020100002160927342",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 363,
                "regionLevel": 1,
                "sequenceIdx": 19,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "20顶层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1659,
                "indexCode": "32020100002160635559",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 500,
                "regionLevel": 1,
                "sequenceIdx": 20,
                "modelUrl": "",
                "cameraUrl": ""
              }
            ]
          },
          {
            "name": "室外",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1705,
            "indexCode": "32020100002160372936",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 661,
            "regionLevel": 0,
            "sequenceIdx": 30,
            "children": [
              {
                "name": "人工地形",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "建筑",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "绿化",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "小品",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "",
                "cameraUrl": ""
              }
            ]
          },
          {
            "name": "地下室",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1650,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "BC区地下室",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "",
                "cameraUrl": ""
              },
              {
                "name": "D区地下室",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "",
                "cameraUrl": ""
              }
            ]
          },
        ]
      }
    ]
  };
  var util = {
    'licenceIP': '192.168.10.34@9059@',
    'SDKPath': '',
    'cmsUrl': 'http://localhost:8088/files',
    'zTreeObj': null
  };
  // ztree 配置
  var setting = {
    check : {
      enable : true,
      autoCheckTrigger : true
    }
  };
  return {
    cmsLayer: cmsLayer,
    util: util,
    setting: setting
  }
 });