'use strict';
/*!
 *
 * @module config
 * @author jg
 * @date 
 * @version V1.0.0
 * @require
 */

 define([
   'layerManage'
 ], function(layerManage) {
  var cmsLayer = {
    'layers': [],
    'nodes': [
      {
        "name": "无锡市人民医院",
        "checked": false,
        "nocheck": false,
        "halfCheck": false,
        "open": true,
        "sid": 1015,
        "controlUnitId": 91,
        "parentId": 52,
        "indexCode": "320201",
        "sequenceIdx": 2,
        "children": [
          {
            "name": "BC区",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1650,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "BC区01层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/BC区/BC区一层/0.c3s.zip",
                "cameraUrl": "camera/BC1FSXT/model/0.c3s.zip"
              },
              {
                "name": "BC区02层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1173,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/BC区/BC区二层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "BC区03层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1251,
                "indexCode": "32020100002160208377",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 396,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "bim_server/320200/BC区/BC区三层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "BC区04层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1316,
                "indexCode": "32020100002160132253",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 397,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "bim_server/320200/BC区/BC区四层/0.c3s.zip",
                "cameraUrl": ""
              }
            ]
          },
          // {
          //   "name": "C区",
          //   "checked": false,
          //   "nocheck": false,
          //   "isParent": true,
          //   "sid": 1657,
          //   "indexCode": "32020100002160650790",
          //   "controlUnitId": 91,
          //   "parentRegionId": 0,
          //   "regionId": 391,
          //   "regionLevel": 0,
          //   "sequenceIdx": 20,
          //   "children": [
          //     {
          //       "name": "C区01层",
          //       "checked": false,
          //       "nocheck": false,
          //       "isParent": false,
          //       "sid": 1058,
          //       "indexCode": "32020100002160138934",
          //       "controlUnitId": 91,
          //       "parentRegionId": 391,
          //       "regionId": 393,
          //       "regionLevel": 1,
          //       "sequenceIdx": 0,
          //       "modelUrl": "",
          //       "cameraUrl": ""
          //     },
          //     {
          //       "name": "C区02层",
          //       "checked": false,
          //       "nocheck": false,
          //       "isParent": false,
          //       "sid": 1174,
          //       "indexCode": "32020100002160990392",
          //       "controlUnitId": 91,
          //       "parentRegionId": 391,
          //       "regionId": 399,
          //       "regionLevel": 1,
          //       "sequenceIdx": 1,
          //       "modelUrl": "",
          //       "cameraUrl": ""
          //     },
          //     {
          //       "name": "C区03层",
          //       "checked": false,
          //       "nocheck": false,
          //       "isParent": false,
          //       "sid": 1252,
          //       "indexCode": "32020100002160081584",
          //       "controlUnitId": 91,
          //       "parentRegionId": 391,
          //       "regionId": 398,
          //       "regionLevel": 1,
          //       "sequenceIdx": 2,
          //       "modelUrl": "",
          //       "cameraUrl": ""
          //     },
          //     {
          //       "name": "C区04层",
          //       "checked": false,
          //       "nocheck": false,
          //       "isParent": false,
          //       "sid": 1315,
          //       "indexCode": "32020100002160453674",
          //       "controlUnitId": 91,
          //       "parentRegionId": 391,
          //       "regionId": 392,
          //       "regionLevel": 1,
          //       "sequenceIdx": 3,
          //       "modelUrl": "",
          //       "cameraUrl": ""
          //     }
          //   ]
          // },
          {
            "name": "D栋",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1665,
            "indexCode": "32020100002160687166",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 287,
            "regionLevel": 0,
            "sequenceIdx": 21,
            "children": [
              {
                "name": "01层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1041,
                "indexCode": "32020100002160903909",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 305,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/D栋/01层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "02层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1156,
                "indexCode": "32020100002160009837",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 300,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/D栋/02层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "03层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1238,
                "indexCode": "32020100002160552485",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 302,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "bim_server/320200/D栋/03层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "04层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1311,
                "indexCode": "32020100002160343416",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 355,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "bim_server/320200/D栋/04层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "05层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1366,
                "indexCode": "32020100002160657540",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 353,
                "regionLevel": 1,
                "sequenceIdx": 4,
                "modelUrl": "bim_server/320200/D栋/05层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "06层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1427,
                "indexCode": "32020100002160951872",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 641,
                "regionLevel": 1,
                "sequenceIdx": 5,
                "modelUrl": "bim_server/320200/D栋/06层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "07层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1456,
                "indexCode": "32020100002160178366",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 364,
                "regionLevel": 1,
                "sequenceIdx": 6,
                "modelUrl": "bim_server/320200/D栋/07层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "08层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1487,
                "indexCode": "32020100002160046699",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 362,
                "regionLevel": 1,
                "sequenceIdx": 7,
                "modelUrl": "bim_server/320200/D栋/08层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "09层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1510,
                "indexCode": "32020100002160498570",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 301,
                "regionLevel": 1,
                "sequenceIdx": 8,
                "modelUrl": "bim_server/320200/D栋/09层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "10层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1533,
                "indexCode": "32020100002160561555",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 295,
                "regionLevel": 1,
                "sequenceIdx": 9,
                "modelUrl": "bim_server/320200/D栋/10层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "11层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1554,
                "indexCode": "32020100002160111093",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 292,
                "regionLevel": 1,
                "sequenceIdx": 10,
                "modelUrl": "bim_server/320200/D栋/11层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "12层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1570,
                "indexCode": "32020100002160623230",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 294,
                "regionLevel": 1,
                "sequenceIdx": 11,
                "modelUrl": "bim_server/320200/D栋/12层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "13层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1584,
                "indexCode": "32020100002160349620",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 299,
                "regionLevel": 1,
                "sequenceIdx": 12,
                "modelUrl": "bim_server/320200/D栋/13层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "14层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1598,
                "indexCode": "32020100002160958948",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 281,
                "regionLevel": 1,
                "sequenceIdx": 13,
                "modelUrl": "bim_server/320200/D栋/14层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "15层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1608,
                "indexCode": "32020100002160997784",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 280,
                "regionLevel": 1,
                "sequenceIdx": 14,
                "modelUrl": "bim_server/320200/D栋/15层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "16层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1618,
                "indexCode": "32020100002160684696",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 288,
                "regionLevel": 1,
                "sequenceIdx": 15,
                "modelUrl": "bim_server/320200/D栋/16层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "17层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1633,
                "indexCode": "32020100002160349076",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 743,
                "regionLevel": 1,
                "sequenceIdx": 16,
                "modelUrl": "bim_server/320200/D栋/17层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "18层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1636,
                "indexCode": "32020100002160402001",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 304,
                "regionLevel": 1,
                "sequenceIdx": 17,
                "modelUrl": "bim_server/320200/D栋/18层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "19层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1642,
                "indexCode": "32020100002160607761",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 365,
                "regionLevel": 1,
                "sequenceIdx": 18,
                "modelUrl": "bim_server/320200/D栋/19层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "20层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1649,
                "indexCode": "32020100002160927342",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 363,
                "regionLevel": 1,
                "sequenceIdx": 19,
                "modelUrl": "bim_server/320200/D栋/20层/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "20顶层",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1659,
                "indexCode": "32020100002160635559",
                "controlUnitId": 91,
                "parentRegionId": 287,
                "regionId": 500,
                "regionLevel": 1,
                "sequenceIdx": 20,
                "modelUrl": "bim_server/320200/D栋/20层顶/0.c3s.zip",
                "cameraUrl": ""
              }
            ]
          },
          {
            "name": "室外",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1705,
            "indexCode": "32020100002160372936",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 661,
            "regionLevel": 0,
            "sequenceIdx": 30,
            "children": [
              {
                "name": "人工地形",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 2059,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/室外/人工地形/0.c3s.zip",
                "cameraUrl": "camera/SWSXT/model/0.c3s.zip"
              },
              {
                "name": "建筑",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1273,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/室外/外壳/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "绿化",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1274,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 2,
                "modelUrl": "bim_server/320200/室外/绿化/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "小品",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1275,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 3,
                "modelUrl": "bim_server/320200/室外/小品/0.c3s.zip",
                "cameraUrl": ""
              }
            ]
          },
          {
            "name": "地下室",
            "checked": false,
            "nocheck": false,
            "isParent": true,
            "sid": 1655,
            "indexCode": "32020100002160387404",
            "controlUnitId": 91,
            "parentRegionId": 0,
            "regionId": 370,
            "regionLevel": 0,
            "sequenceIdx": 19,
            "children": [
              {
                "name": "BC区地下室",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1159,
                "indexCode": "32020100002160338980",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 394,
                "regionLevel": 1,
                "sequenceIdx": 0,
                "modelUrl": "bim_server/320200/地下室/BC区地下室/0.c3s.zip",
                "cameraUrl": ""
              },
              {
                "name": "D区地下室",
                "checked": false,
                "nocheck": false,
                "isParent": false,
                "sid": 1277,
                "indexCode": "32020100002160259060",
                "controlUnitId": 91,
                "parentRegionId": 370,
                "regionId": 395,
                "regionLevel": 1,
                "sequenceIdx": 1,
                "modelUrl": "bim_server/320200/地下室/D区地下室/0.c3s.zip",
                "cameraUrl": ""
              }
            ]
          },
        ]
      }
    ]
  };
  var util = {
    'licenceIP': '192.168.10.34@9059@',
    'SDKPath': '',
    'cmsUrl': 'http://192.168.10.194:8088/files',
    'zTreeObj': null,
  };
  var dom = {
    'domUrl': '/320200/320200/DOM/2018050700',
    'range': [120.311622619629,31.5372848510742,120.324668884277,31.5486145019531],
    'minLevel': 0,
    'maxLevel': 22
  };
  var fullMap = {
    'lon': 120.3192458,
    'lat': 31.54294968,
    'height': 60,
    'azimuth': 4.351113551310101,
    'pitch': -0.6722756375833641,
    'range': 300.9511815746299,
    'time': 3
  };
  // ztree 配置
  var setting = {
    check : {
      enable : true,
      autoCheckTrigger : true
    },
    view : {
      showLine : false
    },
    callback : {
      onCheck : layerManage.showHide,
      onDblClick : layerManage.flyToLayer
    }
  };
  return {
    cmsLayer: cmsLayer,
    util: util,
    dom: dom,
    fullMap: fullMap,
    setting: setting
  }
 });